# Generated by Django 4.2.24 on 2025-09-12 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{6,20}$', 'Enter a valid phone number.')])),
                ('referencia', models.CharField(blank=True, default='móvil', max_length=30)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='contactos.contacto')),
            ],
        ),
    ]
