# Generated by Django 4.2.24 on 2025-09-12 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero_telefono',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{6,20}$', 'Ingrese un número de télefono válido.')]),
        ),
    ]
