version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-agenda_db}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-AdminUnoDos3}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-agenda_db}"]
      interval: 5s
      retries: 10

  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-change-in-production-abc123def456}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost 127.0.0.1 [::1]}
      POSTGRES_DB: ${POSTGRES_DB:-agenda_db}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-AdminUnoDos3}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
